export enum DomainEventType {
  FARMER_BOOKED = 'FARMER_BOOKED',
  BOOKING_CONFIRMED = 'BOOKING_CONFIRMED',
  TOKEN_ASSIGNED = 'TOKEN_ASSIGNED',
  FARMER_ARRIVED = 'FARMER_ARRIVED',
  FARMER_NO_SHOW = 'FARMER_NO_SHOW',
  BOOKING_CANCELLED = 'BOOKING_CANCELLED',
  COUNTER_AVAILABLE = 'COUNTER_AVAILABLE',
  COUNTER_BUSY = 'COUNTER_BUSY',
  WEIGHMENT_STARTED = 'WEIGHMENT_STARTED',
  WEIGHMENT_COMPLETED = 'WEIGHMENT_COMPLETED',
  QUALITY_COMPLETED = 'QUALITY_COMPLETED',
  PROCUREMENT_COMPLETED = 'PROCUREMENT_COMPLETED',
  PAYMENT_STATUS_UPDATED = 'PAYMENT_STATUS_UPDATED',
  CENTRE_CAPACITY_CHANGED = 'CENTRE_CAPACITY_CHANGED',
  SCHEDULING_UPDATED = 'SCHEDULING_UPDATED',
  ETA_UPDATED = 'ETA_UPDATED',
  GOVERNMENT_SYNC_FAILED = 'GOVERNMENT_SYNC_FAILED',
  GOVERNMENT_SYNC_COMPLETED = 'GOVERNMENT_SYNC_COMPLETED',
}

export interface DomainEvent<T = any> {
  eventId: string;
  eventType: DomainEventType;
  timestamp: Date;
  centreId?: string;
  bookingId?: string;
  farmerId?: string;
  payload: T;
  metadata?: Record<string, any>;
}
